#pragma once
#include <SDL.h>
#include <stdlib.h>
#include <time.h>
#include "Player.h"


class Ball
{
private:
	int x;
	int y;
	float vx;
	float vy;
	float initSpeed;
	float speed = initSpeed = 3;
	const float maxSpeed = 10;
	int mySize = 20;
	int screenWidth;
	int screenHeight;

	float pongAngle(int y1, int y2, int height);

public:

	Ball(int screenWidth, int screenHeight);
	SDL_Rect getDestRect();
	void tick();
	void reset();
	void hitPlayer(Player* player);
	int getYCenter();

	//deleting autogenerated constructors;
	Ball() = delete;
	Ball(Ball&) = delete;
	Ball(Ball&&) = delete;
};

