#pragma once
#include <SDL_rect.h>
#include <math.h>
#include <string>

class Player
{
public:
	enum PlayerSide {
		Left,
		Right,
	};

private:
	int score = 0;
	float x;
	float y;
	float speed;
	int screenHeight;
	int screenWidth;
	int myHeight = 80;
	int myWidth = 16;
	PlayerSide mySide;


public:

	Player(int screenWidth, int screenHeight, PlayerSide myPosition);
	SDL_Rect getDestRect();
	std::string getScore();
	void moveUp();
	void moveDown();
	void upScore();
	PlayerSide getSide();

	//deleting autogenerated constructors
	Player() = delete;
	Player(const Player&) = delete;
	Player(const Player&&) = delete;

};

